language: java
jdk:
  - openjdk11
script:
  - ./gradlew check

before_deploy:
##  - gem install faraday-patron -v 1.0.0
##  - gem install bundler -v 1.0.10
  - rvm requirements
  - rvm install 2.6
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 11


deploy:
  provider: heroku
  strategy: git
  api_key: $HEROKU_API_KEY
  app: book-demo-store-bg


