language: java
jdk:
  - openjdk11
script:
  - ./gradlew check

#before_deploy:
##  - gem install faraday-patron -v 1.0.0
##  - gem install bundler -v 1.0.10
#  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.0
before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl --pre
  - gem install bundler
  - yarn install

deploy:
  provider: heroku
  strategy: git
  api_key: $HEROKU_API_KEY
  app: book-demo-store-bg


