spring:
  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    platform: postgresql
    hikari:
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
#springdoc:
#  swagger-ui:
#    path: /swagger-ui-custom.html
